project 'hoge.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# use_frameworks!

target 'hoge' do
end

target 'hogeTests' do
end

target 'hogeUITests' do
end

